In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\Laurent\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.2) or chardet (7.0.1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [2]:
url = "https://www.espn.com/rugby/standings/_/league/180659/sort/gameswon/dir/desc"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

page = requests.get(url, headers=headers)

print(page.status_code)

200

In [3]:
soup = BeautifulSoup(page.text, 'html')
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<!-- ESPNFITT | 8b0710c20ecc | 15929308 | dccea242 | www.espn.com | Sun, 22 Mar 2026 21:06:33 GMT -->
<script>__dataLayer={"pageViewed":false,"helpersEnabled":false,"page":{"author":"","game_id":"","league":"Not Applicable","page_infrastructure":"fitt","placement":"","play_location":"","play_loc_override":"","play_loc_name_override":"","premium":"","purchase_method":"","referer":"","search_query":"","section":"","story_id":"","story_title":"","start_type":"","videoHeaderPresent":"no","videoHeaderAutoplayPresent":"no"},"site":{"portal":"sports","application_name":"Espn Web - Fitt","country":"us","edition":"en-us","site":"espn","language":"en_us","orientation":"desktop"},"pzn":{"affiliate_name":"not authenticated","clientsidetest":"","login_status":"anonymous","betaccountlinked":"no","entitlements":"","has_favorites":"no","hidebetting":"false","has_fantasy":"no","has_notifications":"no","auto_start":"no","userab_1":"","league_manager":"no","paywallshown":"no","isptveauthenticated":"no","ssotveauthenticated":"no","tveauthenticated":"no"},"visitor":{"dssid":"","ad_blocker":"no","wholesale_user":"no","wholesale_mvpd_user":"no","wholesale_provider":"no provider"}}; try{ __dataLayer.visitor = __dataLayer.visitor || {}; __dataLayer.visitor.consent = Object.assign({ isAnonymous: !1 }, JSON.parse(localStorage.getItem('consentToken')).data);}catch(e){}</script>
<script src="https://dcf.espn.com/TWDC-DTCI/prod/Bootstrap.js"></script>
<script>
            (function(h,o,u,n,d) {
                h=h[d]=h[d]||{q:[],onReady:function(c){h.q.push(c)}}
                d=o.createElement(u);d.async=1;d.src=n
                n=o.getElementsByTagName(u)[0];n.parentNode.insertBefore(d,n)
            })(window,document,'script','https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js','DD_RUM');

            window.DD_RUM.onReady(function() {
                window.DD_RUM.setGlobalContext({
                    twdcgrid: {
                        yp_team_id: "67c86818ce5ff1871b58289f",
                        yp_service_id: "67b8d8e244357475ee4bd4b4",
                        datadog_log_index: "observability"
                    }
                });
            });
        </script>
<title data-react-helmet="true">Six Nations Standings - 2026 season - ESPN</title>
<meta content="Visit ESPN for the complete 2026 Six Nations season standings. Includes league, conference and division standings for regular season and playoffs." data-react-helmet="true" name="description"/><meta content="116656161708917" data-react-helmet="true" property="fb:app_id"/><meta content="ESPN" data-react-helmet="true" property="og:site_name"/><meta content="https://www.espn.com/rugby/standings/_/league/180659/sort/gameswon" data-react-helmet="true" property="og:url"/><meta content="Six Nations Standings - 2026 season - ESPN" data-react-helmet="true" property="og:title"/><meta content="Visit ESPN for the complete 2026 Six Nations season standings. Includes league, conference and division standings for regular season and playoffs." data-react-helmet="true" property="og:description"/><meta content="https://a.espncdn.com/combiner/i?img=/redesign/assets/img/icons/ESPN-icon-rugby.png" data-react-helmet="true" property="og:image"/><meta content="500" data-react-helmet="true" property="og:image:width"/><meta content="500" data-react-helmet="true" property="og:image:height"/><meta content="website" data-react-helmet="true" property="og:type"/><meta content="espn" data-react-helmet="true" name="twitter:site"/><meta content="https://www.espn.com/rugby/standings/_/league/180659/sort/gameswon" data-react-helmet="true" name="twitter:url"/><meta content="Six Nations Standings - 2026 season - ESPN" data-react-helmet="true" name="twitter:title"/><meta content="Visit ESPN for the complete 2026 Six Nations season standings. Includes league, conference and division standings for regular season and playoffs." data-react-helmet="true" name="twitter:description"/><meta content="summary" data-react-helmet="true" name="twitter:card"/><meta content="https://a.espncdn.com/combiner/i?img=/redesign/assets/img/icons/ESPN-icon-rugby.png" data-react-helmet="true" name="twitter:image"/><meta content="ESPN" data-react-helmet="true" name="twitter:app:name:iphone"/><meta content="317469184" data-react-helmet="true" name="twitter:app:id:iphone"/><meta content="ESPN" data-react-helmet="true" name="twitter:app:name:googleplay"/><meta content="com.espn.score_center" data-react-helmet="true" name="twitter:app:id:googleplay"/><meta content="Six Nations Standings - 2026 season - ESPN" data-react-helmet="true" name="title"/><meta content="website" data-react-helmet="true" name="medium"/><meta content="noindex" data-react-helmet="true" name="robots"/>
<meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
<meta content="IE=edge" http-equiv="x-ua-compatible"/>
<meta content="en_US" property="og:locale"/>
<link href="//cdn1.espn.net" rel="preconnect"/>
<link crossorigin="" href="https://tredir.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://cdn.registerdisney.go.com" rel="preconnect"/>
<link crossorigin="" href="https://fan.api.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://cdn.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://a.espncdn.com" rel="preconnect"/>
<link crossorigin="" href="https://site.web.api.espn.com" rel="preconnect"/>
<link color="#990000" href="https://a.espncdn.com/prod/assets/icons/E.svg" rel="mask-icon" sizes="any"/>
<link href="https://a.espncdn.com/favicon.ico" rel="shortcut icon"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon-precomposed"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-152x152.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>
<link href="/manifest.json" rel="manifest"/>
<link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/fusion-a45a5d6d.css" rel="stylesheet"><link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/71-c047e00a.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/espnfitt-8c5c5551.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/394-f8f14c08.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/1992-328fafc3.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/css/standings-3e11b2ea.css" rel="stylesheet"/><link data-react-helmet="true" href="https://www.espn.com/rugby/standings/_/league/180659/sort/gameswon" rel="canonical"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Publico/PublicoBannerExtraboldWeb.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBlack.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSansCond/BentonSansCondBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBlack.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansMedium.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansRegular.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteDisplay-CondensedHeavy-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteText-Regular-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Regular-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Bold-Web.woff2" rel="preload" type="font/woff2"/><link data-react-helmet="true" href="android-app://com.espn.score_center/sportscenter/x-callback-url/showClubhouse?uid=undefined&amp;section=standings" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com/rugby/standings/_/league/180659/sort/gameswon" hreflang="en-us" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.br/rugby/classificacao/_/liga/180659/ordenar/gameswon" hreflang="pt-br" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.in/rugby/table/_/league/180659/sort/gameswon" hreflang="en-in" rel="alternate"/><link data-react-helmet="true" href="https://africa.espn.com/rugby/table/_/league/180659/sort/gameswon" hreflang="en-za" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.au/rugby/table/_/league/180659/sort/gameswon" hreflang="en-au" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ve/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-ve" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.cl/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-cl" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.mx/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-mx" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.co/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-co" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.pe/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-pe" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ar/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-ar" rel="alternate"/><link data-react-helmet="true" href="https://espndeportes.espn.com/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-us" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.ph/rugby/table/_/league/180659/sort/gameswon" hreflang="en-ph" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.co.uk/rugby/table/_/league/180659/sort/gameswon" hreflang="en-gb" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.sg/rugby/table/_/league/180659/sort/gameswon" hreflang="en-sg" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.gt/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-gt" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.uy/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-uy" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.do/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-do" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ec/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-ec" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.pa/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-pa" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.co.cr/rugby/posiciones/_/liga/180659/ordenar/gameswon" hreflang="es-cr" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.nl/rugby/stand/_/competitie/180659/sort/gameswon" hreflang="nl-nl" rel="alternate"/>
<script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/runtime-d7ec3265.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/dmp-sdk-4ec14d66.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/71-c075ce6e.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/1609-dac15037.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/9264-abee4af7.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/394-78560395.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/6500-6c720148.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/927-d6dca1ea.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/9429-b9574adc.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/6746-e2a20a3a.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/7253-c038fe6d.js"></script><script defer="" src="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/9637-0fb85319.js"></script>
<link as="script" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/_manifest.js" rel="prefetch"/><link as="script" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/espn-en-444b37b7.js" rel="prefetch"/>
<link as="script" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/espnfitt-0cafb3a2.js" rel="prefetch"/>
<link as="script" href="//cdn1.espn.net/fitt/dccea24281b4-release-03-10-2026.2.0.4308/client/espnfitt/standings-639ac998.js" rel="prefetch"/>
<style id="fittLoadingStyle" type="text/css">
   .page-container,
   .Nav__Primary__Menu,
   .Nav__Secondary__Menu,
    .NavSecondary--GamePackage,
   .SoccerPerformers--gamepackage,
   .ScoreCell__Notes--footer,
   .Gamestrip,
   .Ad:before {
       opacity:                    0;
   }
</style>
<noscript>
<style type="text/css">
                div.HeaderScoreboardContainer, div.Ad, div.sponsored-content { display: none !important; }
                .page-container,
                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item a,
                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item .Nav__Primary__Menu__Link,
                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Title .Nav__Secondary__Menu__Link,
                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Item .Nav__Secondary__Menu__Link {
                    opacity: 1;
                }
            </style>
</noscript>
</link></head>
<body>
<img alt="" height="99999" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHdpZHRoPSI5OTk5OXB4IiBoZWlnaHQ9Ijk5OTk5cHgiIHZpZXdCb3g9IjAgMCA5OTk5OSA5OTk5OSIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48ZyBzdHJva2U9Im5vbmUiIGZpbGw9Im5vbmUiIGZpbGwtb3BhY2l0eT0iMCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9Ijk5OTk5IiBoZWlnaHQ9Ijk5OTk5Ij48L3JlY3Q+IDwvZz4gPC9zdmc+" style="pointer-events: none; position: absolute; top: 0; left: 0; width: 99%; height: 99%; max-width: 99%; max-height: 99%;" width="99999"/>

<h3 style = "color: green; text-align: center">Six Nations Standings - 2026</h3>

In [4]:
table = soup.find_all("span", class_ = "fw-medium")
table

[<span class="fw-medium w-100 dib tar subHeader__item--content"></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Games Played"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/gamesplayed/dir/desc" tabindex="0">GP</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Games Won"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/gameswon/dir/asc" tabindex="0">W<svg aria-hidden="true" class="ArrowIcon__TableSort icon__svg" style="display:inline-block;height:10px;width:10px;margin-left:4px" viewbox="0 0 24 24"><use xlink:href="#icon__caret__down"></use></svg></a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Games Drawn"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/gamesdrawn/dir/desc" tabindex="0">D</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Games Lost"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/gameslost/dir/desc" tabindex="0">L</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Bye Games"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/gamesbye/dir/desc" tabindex="0">BYE</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Points For"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/pointsfor/dir/desc" tabindex="0">F</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Points Against"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/pointsagainst/dir/desc" tabindex="0">A</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Tries For"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/triesfor/dir/desc" tabindex="0">TF</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Tries Against"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/triesagainst/dir/desc" tabindex="0">TA</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Bonus Points Try"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/bonuspointstry/dir/desc" tabindex="0">TBP</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Bonus Points Losing"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/bonuspointslosing/dir/desc" tabindex="0">LBP</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Bonus Points"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/bonuspoints/dir/desc" tabindex="0">BP</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Points Difference"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/pointsdifference/dir/desc" tabindex="0">PD</a></span>,
 <span class="fw-medium w-100 dib tar subHeader__item--content underline" title="Points"><a class="AnchorLink" href="/rugby/standings/_/league/180659/sort/points/dir/desc" tabindex="0">P</a></span>]

In [5]:
columns_name = table[1:]

standing_column = [rugby.text.strip() for rugby in columns_name]
print(standing_column)

['GP', 'W', 'D', 'L', 'BYE', 'F', 'A', 'TF', 'TA', 'TBP', 'LBP', 'BP', 'PD', 'P']

In [6]:
# Countries
countries = soup.find_all("span", class_ = "hide-mobile")

column_countries = [countrie.text.strip() for countrie  in countries]
print(column_countries)

['France', 'Ireland', 'Scotland', 'Italy', 'England', 'Wales']

In [7]:
# Colonne dans df1
df = pd.DataFrame(columns = column_countries, index = standing_column)
df.head(2)

   France Ireland Scotland Italy England Wales
GP    NaN     NaN      NaN   NaN     NaN   NaN
W     NaN     NaN      NaN   NaN     NaN   NaN

In [8]:
# Column France

france = soup.find_all("span", class_ = "stat-cell")[0:14]

row_france = [rows.text.strip() for rows in france]
print(row_france)

# Column Ireland

ireland = soup.find_all("span", class_ = "stat-cell")[14:28]

row_ireland = [rows.text.strip() for rows in ireland]
print(row_ireland)

# Column Scotland

scotland = soup.find_all("span", class_= 'stat-cell')[28:42]

row_scotland= [rows.text.strip() for rows in scotland]
print(row_scotland)

# Column Italy

italy = soup.find_all("span", class_= 'stat-cell')[42:56]

row_italy = [rows.text.strip() for rows in italy]
print(row_italy)

# Column England
england = soup.find_all("span", class_= 'stat-cell')[56:70]

row_england = [rows.text.strip() for rows in england]
print(row_england)

# Column Walles
wales = soup.find_all("span", class_= 'stat-cell')[70:]

row_wales = [rows.text.strip() for rows in wales]
print(row_wales)

['5', '4', '0', '1', '0', '211', '130', '30', '19', '5', '0', '5', '+81', '21']
['5', '4', '0', '1', '0', '146', '108', '20', '14', '3', '0', '3', '+38', '19']
['5', '3', '0', '2', '0', '143', '144', '20', '18', '3', '1', '4', '-1', '16']
['5', '2', '0', '3', '0', '79', '117', '9', '16', '0', '1', '1', '-38', '9']
['5', '1', '0', '4', '0', '153', '151', '21', '18', '2', '2', '4', '+2', '8']
['5', '1', '0', '4', '0', '90', '172', '11', '26', '1', '1', '2', '-82', '6']

In [9]:
# Création des titres des colonnes du DF
#df = pd.DataFrame(columns = rugby_column)

# Remplir le DF et chaque colonne avec les données
df["France"] = row_france
df["Ireland"] = row_ireland
df["Scotland"] = row_scotland
df["Italy"] = row_italy
df["England"] = row_england
df["Wales"] = row_wales

df

    France Ireland Scotland Italy England Wales
GP       5       5        5     5       5     5
W        4       4        3     2       1     1
D        0       0        0     0       0     0
L        1       1        2     3       4     4
BYE      0       0        0     0       0     0
F      211     146      143    79     153    90
A      130     108      144   117     151   172
TF      30      20       20     9      21    11
TA      19      14       18    16      18    26
TBP      5       3        3     0       2     1
LBP      0       0        1     1       2     1
BP       5       3        4     1       4     2
PD     +81     +38       -1   -38      +2   -82
P       21      19       16     9       8     6

In [10]:
df = df.transpose()

In [11]:
df = df.reset_index()

In [12]:
df.head()

      index GP  W  D  L BYE    F    A  TF  TA TBP LBP BP   PD   P
0    France  5  4  0  1   0  211  130  30  19   5   0  5  +81  21
1   Ireland  5  4  0  1   0  146  108  20  14   3   0  3  +38  19
2  Scotland  5  3  0  2   0  143  144  20  18   3   1  4   -1  16
3     Italy  5  2  0  3   0   79  117   9  16   0   1  1  -38   9
4   England  5  1  0  4   0  153  151  21  18   2   2  4   +2   8

In [13]:
df.rename(columns={"index": "Country"}, inplace=True)

In [14]:
df.to_csv("../../data/standings.csv", index=False)